export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "surface-container": "#edeeef",
        "surface": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-container": "#dfdfe9",
        "on-tertiary-fixed": "#410007",
        "primary-fixed-dim": "#98cdf2",
        "on-secondary-fixed": "#191b22",
        "inverse-primary": "#98cdf2",
        "tertiary-container": "#dc3240",
        "on-secondary-fixed-variant": "#45464e",
        "on-tertiary-container": "#fffdff",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
        "tertiary": "#b9122b",
        "surface-container-high": "#e7e8e9",
        "surface-variant": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "outline": "#71787e",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface-tint": "#2b6485",
        "surface-dim": "#d9dadb",
        "on-surface-variant": "#41484d",
        "on-primary-container": "#fffdff",
        "tertiary-fixed": "#ffdad8",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c5c6cf",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed-variant": "#92001c",
        "secondary-fixed": "#e2e2ec",
        "primary-fixed": "#c7e7ff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb3b1",
        "secondary": "#5c5e66",
        "primary": "#296283",
        "on-primary-fixed-variant": "#064c6b",
        "primary-container": "#457b9d",
        "on-secondary-container": "#61626b",
        "on-secondary": "#ffffff",
        "outline-variant": "#c1c7ce",
        "on-primary-fixed": "#001e2e"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
